//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsBiddingUsingBootstrap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars_Info()
        {
            this.Biddings = new HashSet<Bidding>();
            this.Insurances = new HashSet<Insurance>();
            this.NotificationHistories = new HashSet<NotificationHistory>();
        }
    
        public int CarId { get; set; }
        public string TypeOfCar { get; set; }
        public string ColorOfCar { get; set; }
        public string EngineCapacity { get; set; }
        public Nullable<int> YearOfManufacture { get; set; }
        public Nullable<int> InitialPrice { get; set; }
        public string CarChecking { get; set; }
        public string Description { get; set; }
        public string MainPhoto { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public string Photo3 { get; set; }
        public string Photo4 { get; set; }
        public string Photo5 { get; set; }
        public Nullable<bool> InsuranceForSale { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> CarCustoms { get; set; }
        public Nullable<int> CarInsurance { get; set; }
        public Nullable<bool> CarLicense { get; set; }
        public Nullable<bool> TypeOfTransmissionGear { get; set; }
        public Nullable<int> Kilometers { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<bool> Timer_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bidding> Biddings { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insurance> Insurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationHistory> NotificationHistories { get; set; }
    }
}
