//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsBiddingUsingBootstrap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarsBiddingEntities : DbContext
    {
        public CarsBiddingEntities()
            : base("name=CarsBiddingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bidding> Biddings { get; set; }
        public virtual DbSet<Cars_Info> Cars_Info { get; set; }
        public virtual DbSet<Insurance> Insurances { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<NotificationHistory> NotificationHistories { get; set; }
    }
}
