//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsBiddingUsingBootstrap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarsBiddingTemplateTest.LocalizationRecource.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Photo.
        /// </summary>
        public static string AdditionalPhoto {
            get {
                return ResourceManager.GetString("AdditionalPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Car.
        /// </summary>
        public static string AddNewCar {
            get {
                return ResourceManager.GetString("AddNewCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The following picture represent example how to add new car in correct way:.
        /// </summary>
        public static string AddNewCarFigure {
            get {
                return ResourceManager.GetString("AddNewCarFigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new car has been added to gallery successfully..
        /// </summary>
        public static string AddNewCarSuccessfully {
            get {
                return ResourceManager.GetString("AddNewCarSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any electronic process aimed at reducing the time and effort on the user, and thus Bidding Cars aims to speed up the process of selling cars in less time and effort on the user.
        /// </summary>
        public static string AnyElectronicProcessAimedAtReducingThe {
            get {
                return ResourceManager.GetString("AnyElectronicProcessAimedAtReducingThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction Time Ended..
        /// </summary>
        public static string AuctionTimeEnded {
            get {
                return ResourceManager.GetString("AuctionTimeEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Gear.
        /// </summary>
        public static string AutomaticGear {
            get {
                return ResourceManager.GetString("AutomaticGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidding.
        /// </summary>
        public static string Bidding {
            get {
                return ResourceManager.GetString("Bidding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidding Process.
        /// </summary>
        public static string BiddingProcess {
            get {
                return ResourceManager.GetString("BiddingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to be able to participate in the bidding process..
        /// </summary>
        public static string BiddingProcessErrorMsg {
            get {
                return ResourceManager.GetString("BiddingProcessErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid process completed successfully..
        /// </summary>
        public static string BidProcessSuccessfully {
            get {
                return ResourceManager.GetString("BidProcessSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDay.
        /// </summary>
        public static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Color.
        /// </summary>
        public static string CarColor {
            get {
                return ResourceManager.GetString("CarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Customs.
        /// </summary>
        public static string CarCustoms {
            get {
                return ResourceManager.GetString("CarCustoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Details.
        /// </summary>
        public static string CarDetails {
            get {
                return ResourceManager.GetString("CarDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Insurance.
        /// </summary>
        public static string CarInsurance {
            get {
                return ResourceManager.GetString("CarInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car License.
        /// </summary>
        public static string CarLicense {
            get {
                return ResourceManager.GetString("CarLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars Bidding.
        /// </summary>
        public static string Cars_Bidding {
            get {
                return ResourceManager.GetString("Cars Bidding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars Bidding.
        /// </summary>
        public static string CarsBidding {
            get {
                return ResourceManager.GetString("CarsBidding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} Car sold successfully..
        /// </summary>
        public static string CarSoldSuccessfully {
            get {
                return ResourceManager.GetString("CarSoldSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Type.
        /// </summary>
        public static string CarType {
            get {
                return ResourceManager.GetString("CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB.
        /// </summary>
        public static string CB {
            get {
                return ResourceManager.GetString("CB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Car.
        /// </summary>
        public static string CheckingCar {
            get {
                return ResourceManager.GetString("CheckingCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} and {1} do not match..
        /// </summary>
        public static string CompareValidation {
            get {
                return ResourceManager.GetString("CompareValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive Insurance.
        /// </summary>
        public static string ComprehensiveInsurance {
            get {
                return ResourceManager.GetString("ComprehensiveInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardens Street, Shakshir Building, Third Floor , Jordan..
        /// </summary>
        public static string ContactLocation {
            get {
                return ResourceManager.GetString("ContactLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you to contact with us,&lt;br/&gt; we will review your message then will we contact with you as soon as possible..
        /// </summary>
        public static string ContactResponseMessage {
            get {
                return ResourceManager.GetString("ContactResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *CreditCardField:.
        /// </summary>
        public static string CreditCardField {
            get {
                return ResourceManager.GetString("CreditCardField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You should provide 50 JD as a deposit money to guarantee that you will sell the car and as a protection on our part..
        /// </summary>
        public static string CreditCardFieldText {
            get {
                return ResourceManager.GetString("CreditCardFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number.
        /// </summary>
        public static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Price.
        /// </summary>
        public static string CurrentPrice {
            get {
                return ResourceManager.GetString("CurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days  ago.
        /// </summary>
        public static string DAYS {
            get {
                return ResourceManager.GetString("DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined new user successfully..
        /// </summary>
        public static string DefinedUserSuccessfully {
            get {
                return ResourceManager.GetString("DefinedUserSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details About 50JD.
        /// </summary>
        public static string Detailsabout50JD {
            get {
                return ResourceManager.GetString("Detailsabout50JD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should provide 50 JD as a deposit money to guarantee that you will sell the car and as a protection on our part and We will refund the deposit money (50 JD) when:.
        /// </summary>
        public static string Detailsabout50jdText {
            get {
                return ResourceManager.GetString("Detailsabout50jdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email..
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Car.
        /// </summary>
        public static string EngineCar {
            get {
                return ResourceManager.GetString("EngineCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Email....
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A few seconds ago.
        /// </summary>
        public static string FEWSECONDS {
            get {
                return ResourceManager.GetString("FEWSECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only images can be uploaded..
        /// </summary>
        public static string FileTypeValidation {
            get {
                return ResourceManager.GetString("FileTypeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Price.
        /// </summary>
        public static string FinalPrice {
            get {
                return ResourceManager.GetString("FinalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please fill all search inputs..
        /// </summary>
        public static string GalleryMultiSearchTextInputRequiredField {
            get {
                return ResourceManager.GetString("GalleryMultiSearchTextInputRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours  ago.
        /// </summary>
        public static string HOURS {
            get {
                return ResourceManager.GetString("HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However,the deposit money (50 JD) will not be refunded if the owner of the car cancels the bidding process or sale..
        /// </summary>
        public static string However {
            get {
                return ResourceManager.GetString("However", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The greatest number of  image that you can upload is 5 image..
        /// </summary>
        public static string ImageNumberValidation {
            get {
                return ResourceManager.GetString("ImageNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size must be less than 2MB..
        /// </summary>
        public static string ImageSize {
            get {
                return ResourceManager.GetString("ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each image size must be less than 2MB..
        /// </summary>
        public static string ImageSizeV2 {
            get {
                return ResourceManager.GetString("ImageSizeV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Price.
        /// </summary>
        public static string InitialPrice {
            get {
                return ResourceManager.GetString("InitialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should provide 50 JD as a deposit money to guarantee that you will purchase the car and as a protection on our part and We will refund the deposit money (50 JD) when:.
        /// </summary>
        public static string InsuranceDetails {
            get {
                return ResourceManager.GetString("InsuranceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A- the car is purchased successfully..
        /// </summary>
        public static string InsuranceDetailsA {
            get {
                return ResourceManager.GetString("InsuranceDetailsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B- the car owner cancels the sell of the car..
        /// </summary>
        public static string InsuranceDetailsB {
            get {
                return ResourceManager.GetString("InsuranceDetailsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However,the deposit money (50 JD) will not be refunded if the buyer cancels the purchase of the car after participating in the bidding process ..
        /// </summary>
        public static string InsuranceDetailsHowever {
            get {
                return ResourceManager.GetString("InsuranceDetailsHowever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The insurance has been paid successfully, you can now participate in the bidding process..
        /// </summary>
        public static string InsurancePaidSuccessfully {
            get {
                return ResourceManager.GetString("InsurancePaidSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a system directed mainly to those who want to sell or buy their used cars through an auction.
        /// </summary>
        public static string IsASystemDirectedMainlyToThoseWhoWantToSellOrBuyTheirUsedCarsThroughAnAuction {
            get {
                return ResourceManager.GetString("IsASystemDirectedMainlyToThoseWhoWantToSellOrBuyTheirUsedCarsThroughAnAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string isRTL {
            get {
                return ResourceManager.GetString("isRTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JD.
        /// </summary>
        public static string JD {
            get {
                return ResourceManager.GetString("JD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langauge.
        /// </summary>
        public static string Langauge {
            get {
                return ResourceManager.GetString("Langauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Photo.
        /// </summary>
        public static string MainPhoto {
            get {
                return ResourceManager.GetString("MainPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *MainPhotoField: .
        /// </summary>
        public static string MainPhotoField {
            get {
                return ResourceManager.GetString("MainPhotoField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main photo is the one that we will use in the gallery section..
        /// </summary>
        public static string MainPhotoToolTip {
            get {
                return ResourceManager.GetString("MainPhotoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory Insurance.
        /// </summary>
        public static string MandatoryInsurance {
            get {
                return ResourceManager.GetString("MandatoryInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture  Year.
        /// </summary>
        public static string ManufactureYear {
            get {
                return ResourceManager.GetString("ManufactureYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the year consisting of 4 digits..
        /// </summary>
        public static string ManufactureYearValidation {
            get {
                return ResourceManager.GetString("ManufactureYearValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message . . ..
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes  ago.
        /// </summary>
        public static string MINUTES {
            get {
                return ResourceManager.GetString("MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Months ago.
        /// </summary>
        public static string MONTHS {
            get {
                return ResourceManager.GetString("MONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be less than 10 character,without space and not mixing Ar-En..
        /// </summary>
        public static string NameValidation {
            get {
                return ResourceManager.GetString("NameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Car.
        /// </summary>
        public static string NewCar {
            get {
                return ResourceManager.GetString("NewCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Price.
        /// </summary>
        public static string NewPrice {
            get {
                return ResourceManager.GetString("NewPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new price should be greater than current price..
        /// </summary>
        public static string NewPriceValidation {
            get {
                return ResourceManager.GetString("NewPriceValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Gear.
        /// </summary>
        public static string NormalGear {
            get {
                return ResourceManager.GetString("NormalGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Gallery does not contain any car.
        /// </summary>
        public static string NotFoundData {
            get {
                return ResourceManager.GetString("NotFoundData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Details.
        /// </summary>
        public static string NotificationDetails {
            get {
                return ResourceManager.GetString("NotificationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Email.
        /// </summary>
        public static string OwnerEmail {
            get {
                return ResourceManager.GetString("OwnerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Phone Number.
        /// </summary>
        public static string OwnerPhoneNumber {
            get {
                return ResourceManager.GetString("OwnerPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be consists from 8 character(at least one number &amp; letter) without space..
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter Jordanian valid phone number which start with 07..
        /// </summary>
        public static string PhoneNumberValidation {
            get {
                return ResourceManager.GetString("PhoneNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the {0} field must be greater than zero..
        /// </summary>
        public static string PostiveNumberValidation {
            get {
                return ResourceManager.GetString("PostiveNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the price field must be greater than zero..
        /// </summary>
        public static string PriceSearchTextInputValidation {
            get {
                return ResourceManager.GetString("PriceSearchTextInputValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should provide 50 JD as a deposit money to guarantee that you will purchase the car and as a protection on our part..
        /// </summary>
        public static string PurchaseInsuranceToolTip {
            get {
                return ResourceManager.GetString("PurchaseInsuranceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-the car is sold successfully..
        /// </summary>
        public static string RefundmoneycaseOne {
            get {
                return ResourceManager.GetString("RefundmoneycaseOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C- the customer cancels the purchase of the car..
        /// </summary>
        public static string RefundmoneycaseThree {
            get {
                return ResourceManager.GetString("RefundmoneycaseThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-the bidding time has expired and nobody buy the car..
        /// </summary>
        public static string RefundmoneycaseTwo {
            get {
                return ResourceManager.GetString("RefundmoneycaseTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now.
        /// </summary>
        public static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string RequiredFieldValidation {
            get {
                return ResourceManager.GetString("RequiredFieldValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The car that you are looking for doesn&apos;t exists..
        /// </summary>
        public static string SearchNotFound {
            get {
                return ResourceManager.GetString("SearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- SearchType --.
        /// </summary>
        public static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds  ago.
        /// </summary>
        public static string SECONDS {
            get {
                return ResourceManager.GetString("SECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe Our News letter.
        /// </summary>
        public static string SubscribeOurNewsletter {
            get {
                return ResourceManager.GetString("SubscribeOurNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Colors.
        /// </summary>
        public static string ThemeColor {
            get {
                return ResourceManager.GetString("ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Purchase Insurance.
        /// </summary>
        public static string ThePurchaseInsurance {
            get {
                return ResourceManager.GetString("ThePurchaseInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are&apos;nt any notification.
        /// </summary>
        public static string ThereAre_ntAnyNotification_ {
            get {
                return ResourceManager.GetString("ThereAre\'ntAnyNotification.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Remaining Time For Auction Ending.
        /// </summary>
        public static string TheRemainingTimeForAuctionEnding {
            get {
                return ResourceManager.GetString("TheRemainingTimeForAuctionEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system of sale and purchase of used cars by auction,is a system directed mainly to those who want to sell or buy their used cars through an auction. Working on the system of buying and selling by bidding, solve problems in other traditional systems, such as: Credibility and seriousness in selling and buying.
        /// </summary>
        public static string TheSystemOfSaleAndPurchaseOfUsedCarsByAuctionIsASyst {
            get {
                return ResourceManager.GetString("TheSystemOfSaleAndPurchaseOfUsedCarsByAuctionIsASyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Transmission Gear.
        /// </summary>
        public static string TypeOfTransmissionGear {
            get {
                return ResourceManager.GetString("TypeOfTransmissionGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is already exists..
        /// </summary>
        public static string UniqueFieldValidaion {
            get {
                return ResourceManager.GetString("UniqueFieldValidaion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username or password is incorrect..
        /// </summary>
        public static string UserLoginValidation {
            get {
                return ResourceManager.GetString("UserLoginValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter valid username or email..
        /// </summary>
        public static string UserNameEmailValidation {
            get {
                return ResourceManager.GetString("UserNameEmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be without space and not mixing Ar-En(can you use _ symbol)..
        /// </summary>
        public static string UserNameValidation {
            get {
                return ResourceManager.GetString("UserNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Weeks  ago.
        /// </summary>
        public static string WEEKS {
            get {
                return ResourceManager.GetString("WEEKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s the Cars Bidding?.
        /// </summary>
        public static string What_sTheCarsBidding {
            get {
                return ResourceManager.GetString("What\'sTheCarsBidding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner Email.
        /// </summary>
        public static string WinnerEmail {
            get {
                return ResourceManager.GetString("WinnerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner Name.
        /// </summary>
        public static string WinnerName {
            get {
                return ResourceManager.GetString("WinnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner Phone Number.
        /// </summary>
        public static string WinnerPhoneNumber {
            get {
                return ResourceManager.GetString("WinnerPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Customs.
        /// </summary>
        public static string WithCustoms {
            get {
                return ResourceManager.GetString("WithCustoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With License.
        /// </summary>
        public static string WithLicense {
            get {
                return ResourceManager.GetString("WithLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Customs.
        /// </summary>
        public static string WithoutCustoms {
            get {
                return ResourceManager.GetString("WithoutCustoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Insurance.
        /// </summary>
        public static string WithoutInsurance {
            get {
                return ResourceManager.GetString("WithoutInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without License.
        /// </summary>
        public static string WithoutLicense {
            get {
                return ResourceManager.GetString("WithoutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be without space..
        /// </summary>
        public static string WithoutSpaceRgexValidation {
            get {
                return ResourceManager.GetString("WithoutSpaceRgexValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on the system of buying and selling by bidding, solve problems in other traditional systems, such as: Credibility and seriousness in selling and buying.
        /// </summary>
        public static string WorkingOnTheSystemOfBuyingAndSellingByBiddingSolveProblemsInOtherTraditionalSystemsSuchAsCredibilityAndSeriousnessInSellingAndBuying {
            get {
                return ResourceManager.GetString("WorkingOnTheSystemOfBuyingAndSellingByBiddingSolveProblemsInOtherTraditionalSyste" +
                        "msSuchAsCredibilityAndSeriousnessInSellingAndBuying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Years ago.
        /// </summary>
        public static string YEARS {
            get {
                return ResourceManager.GetString("YEARS", resourceCulture);
            }
        }
    }
}
